spring.application.name=StudentCourseApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/CourseStudentDB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


ai.api.url=https://api.openai.com/v1/chat/completions
ai.api.key=${OPENAI_API_KEY}
ai.model=gpt-4o-mini
