spring.application.name=StudentCourseApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/CourseStudentDB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


ai.api.url=https://api.openai.com/v1/chat/completions
ai.api.key=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
ai.model=gpt-4o-mini
